#### Questions and thoughts from yesterday

In [1]:
# return and print in a function

In [2]:
def add_subtract(a, b):
    summ = a + b
    difference = a - b
    result = [summ, difference]
    return result

def add_subtract(a, b):
    summ = a + b
    difference = a - b
    
    # this is basically the same as the previous approach
    return summ, difference


In [6]:
x = 2
y = 10

z = add_subtract(b=y, a=x)

print(z[0])
print(z[1])

12
-8


In [8]:
# don't dwell on this, it's a shortcut
[c,f] = add_subtract(b=y, a=x)

print(c)
print(f)

12
-8


In [14]:
X = 5
B = 7

z = add_subtract(X, B)

t = add_subtract(z[0], z[1])

s = add_subtract(t[0], t[1])

# "very advanced, do not worry about this":
z = add_subtract(X, B)
# z is now a list of 2 items
add_subtract(*z) # "unpack" z into this function

(10, 14)

In [16]:
# a review `for` loop

my_organisms = ['E. coli', 'Mouse', 'Elephant', 'Poison ivy']
their_domains = ['prokaryote', 'eukaryote', 'eukaryote', 'eukaryote']

last = len(my_organisms)

for x in range(0,last):
    print(my_organisms[x])
    print(their_domains[x])

E. coli
prokaryote
Mouse
eukaryote
Elephant
eukaryote
Poison ivy
eukaryote


In [17]:
# extra advanced tip; ignore if it confuses you

for organism, domain in zip(my_organisms, their_domains):
    print(organism)
    print(domain)

E. coli
prokaryote
Mouse
eukaryote
Elephant
eukaryote
Poison ivy
eukaryote


<hr/>
### `import`

In [19]:
# a module: a file or bunch of files of python code somewhere else
# os is a module
import os

In [23]:
os.getcwd() # getcwd is a function inside the `os` module

'/Users/ben/code/PNI_Programming_Statistics_Bootcamp_2018/Week1_Python/Day4'

In [24]:
def getcwd(x):
    result = x*2
    return result

In [25]:
getcwd(4)

os.

8

In [26]:
filename = 'my_image.tif'

os.path.splitext(filename) # the "split extension" function in the os.path module

('my_image', '.tif')

<hr/>
When trouble arises: stop, hands off keyboard, think of your plan, and begin again.

<hr/>
### `numpy`

#### *num*erical *py*thon

In [31]:
# import

import numpy

# a trick:
import numpy as np # immediately renames numpy to np

In [32]:
# 1D array

my_list = [1, 22, 9, -1, 0.3]

my_array = np.array( my_list )

In [33]:
print(my_array)

[ 1.  22.   9.  -1.   0.3]


In [36]:
my_array = np.array([1,2,3,4]) 
# we most commonly make an array by converting a python list into an array

In [37]:
my_list = [1,2,3,4]

type(my_array)

numpy.ndarray

In [38]:
len(my_array)

4

In [40]:
my_array = np.array(['a', 'b', 'c', 'd'])

print(my_array)

['a' 'b' 'c' 'd']


In [41]:
# dtype : data type

my_array = np.array([1,2,3,4,5])

print(my_array.dtype)

int64


In [42]:
my_array = np.array([0.5, 1.1, 2.7, 3.9])

print(my_array.dtype)

float64


In [43]:
my_array = np.array([1, 2, 3, 4.5, 6.5, 7.5])

print(my_array.dtype)

float64


In [44]:
my_array = np.array(['a', 'b', 'c', 'd'])

print(my_array.dtype)

<U1


In [45]:
# indexing and assignments (review)

my_array = np.array([0,1,2,3,4,5,6,7,8,9])

# how can we get the first 3 items?
my_array[0:3]


array([0, 1, 2])

In [50]:
# can we index it backwards?

my_array[::-1]

array([5, 4, 3, 2, 1, 0])

In [51]:
# how about step sizes other than 1?

my_array[::2]

array([0, 2, 4])

In [47]:
# printing out lists and array

my_list = [0,1,2,3,4,5]
my_array = np.array(my_list)


print('List:', my_list)
print('Array:', my_array)

List: [0, 1, 2, 3, 4, 5]
Array: [0 1 2 3 4 5]


In [49]:
my_array

array([0, 1, 2, 3, 4, 5])

In [54]:
my_mixed_array = np.array(['a', 22, 'b', 44])

print(my_mixed_array)

print(my_mixed_array.dtype)

['a' '22' 'b' '44']
<U2


In [16]:
# reminders: lists vs arrays

In [56]:
my_name = 'Ben'

my_array = np.array([1,2,3,4,5])

### problem set

In [57]:
# vector math: +/-/*/, >/</==, with scalars/vectors etc.

my_list = [1,2,3,4]

print(my_list * 2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [59]:
my_array = np.array([1,2,3,4])

print(my_array * 2)

# our first major difference in the behaviour of lists vs arrays

[2 4 6 8]


In [60]:
my_array = np.array([1,2,3,4])

my_array = my_array * 2

my_array = my_array + 3

print(my_array)

[ 5  7  9 11]


In [ ]:
# the first lesson about arrays: when you do math on them,
# the math gets done to every element in the array individually.
# that is not what lists did!

In [ ]:
# how can we concatenate a new number onto the array?

# with a list, we could do:
my_list = [1,2,3]
my_new_list = my_list + [4]

# with a numpy array, here is one approach:
my_array = np.array([1,2,3,4])
my_array = np.append(my_array, 5)
# don't confuse that with how list append works, reminder:

my_list = [1,2,3]
my_list.append(4)
# NOT:
# my_list = my_list.append(4)

In [61]:
# vector math: +/-/*/, >/</==, with scalars/vectors etc.
# arange, linspace

In [62]:
my_array = np.array([2,4,6,8,10,12])

x = 10

my_new_array = my_array * x

print(my_new_array)

[ 20  40  60  80 100 120]


In [64]:
my_array = np.array([2,4,6,8,10,12])

print( my_array > 5 )

print( my_array == my_array*2 )

[False False  True  True  True  True]
[False False False False False False]


In [67]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4])

print( arr1 == arr2 )

False


/Users/ben/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:4: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  after removing the cwd from sys.path.


In [68]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [71]:
np.arange # array range --> arange

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:

np.linspace(20, 30, 21)


array([20. , 20.5, 21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. ,
       25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5, 30. ])

In [80]:
np.arange(step=0.1, start=50, stop=100+0.1)

array([ 50. ,  50.1,  50.2,  50.3,  50.4,  50.5,  50.6,  50.7,  50.8,
        50.9,  51. ,  51.1,  51.2,  51.3,  51.4,  51.5,  51.6,  51.7,
        51.8,  51.9,  52. ,  52.1,  52.2,  52.3,  52.4,  52.5,  52.6,
        52.7,  52.8,  52.9,  53. ,  53.1,  53.2,  53.3,  53.4,  53.5,
        53.6,  53.7,  53.8,  53.9,  54. ,  54.1,  54.2,  54.3,  54.4,
        54.5,  54.6,  54.7,  54.8,  54.9,  55. ,  55.1,  55.2,  55.3,
        55.4,  55.5,  55.6,  55.7,  55.8,  55.9,  56. ,  56.1,  56.2,
        56.3,  56.4,  56.5,  56.6,  56.7,  56.8,  56.9,  57. ,  57.1,
        57.2,  57.3,  57.4,  57.5,  57.6,  57.7,  57.8,  57.9,  58. ,
        58.1,  58.2,  58.3,  58.4,  58.5,  58.6,  58.7,  58.8,  58.9,
        59. ,  59.1,  59.2,  59.3,  59.4,  59.5,  59.6,  59.7,  59.8,
        59.9,  60. ,  60.1,  60.2,  60.3,  60.4,  60.5,  60.6,  60.7,
        60.8,  60.9,  61. ,  61.1,  61.2,  61.3,  61.4,  61.5,  61.6,
        61.7,  61.8,  61.9,  62. ,  62.1,  62.2,  62.3,  62.4,  62.5,
        62.6,  62.7,

In [82]:
np.linspace(0, 10, 11)

np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

### problem set

In [85]:
# max, min, sum, mean, median, std

my_array = np.array([22, 10, 1, 20, 30, 2, 1])

result = np.sum(my_array)

print(result)

86


In [90]:
print( np.std(my_array) )

10.911517973673321


In [94]:
# any, all

my_array = np.array([10, 11, 12, 13])

result = my_array > 5

print(result)

# a manual approach
are_they_all_true = np.sum(result) == len(my_array)
print(are_they_all_true)

# the easier way
are_they_all_true = np.all(result)
print(are_they_all_true)

# in summary:
# if we want to know whether all values are greater than 5:
print( np.all(my_array>5) )

[ True  True  True  True]
True
True
True


In [96]:
my_array = np.array([10, 11, 12, 13])

print('Are any values greater than 10:', np.any(my_array > 10))
print('Are any values less than 10:', np.any(my_array < 10))

Are any values greater than 10: True
Are any values less than 10: False


In [97]:
# unique

arr = np.array([10, 10, 10, 20, 20, 20, 30, 30, 30])

np.unique(arr)

array([10, 20, 30])

In [98]:
# abs, log, round, sort

my_array = np.array([1.2, 2.2, 3.4, 3.2, 4.5])

np.round(my_array)

array([1., 2., 3., 3., 4.])

In [99]:
# divide by zero

my_array = np.arange(10, 50, .2)

print( my_array / 0 )

[inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
 inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
 inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
 inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
 inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
 inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
 inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
 inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
 inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
 inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
 inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
 inf inf]


/Users/ben/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


In [102]:
my_array = np.array([1, 2, 3, 50, 6, 7])

# what is the largest value?
# at which index in the array is that largest value?

largest_value = np.max(my_array)
print('The largest value is', largest_value)

index_of_largest_value = np.argmax(my_array)
print('The index of the largest value is', index_of_largest_value)


The largest value is 50
The index of the largest value is 3


In [ ]:
np.argmax

In [15]:
# (use google to discover a function related to max/min)

### problem set

In [120]:
# 2d array

my_list = [[1,2,3], [4,5,6], [7,8,9]]


print(my_list[0])

# shape

[1, 2, 3]


In [133]:
my_list = [
            [1,2,3], # row0 
            [4,5,6], # row1
            [7,8,9],  # row2
            [10,11,12]  # row3
          ]

print(my_list[0])

[1, 2, 3]


In [134]:
my_2d_array = np.array(my_list)

print(my_2d_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [135]:
print(my_2d_array[1])

[4 5 6]


In [136]:
print( my_2d_array.shape )

# both correct:
# (number of lists, size of lists)
# (rows, columns)

(4, 3)


In [139]:
my_2d_array[3]
my_2d_array[-1]

array([10, 11, 12])

In [140]:
print(my_2d_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [144]:
row1 = my_2d_array[1]
print(row1)

item1 = row1[1]
print(item1)

item = my_2d_array[1][1]

[4 5 6]
5


In [146]:
my_2d_array[1,1] # [row_index, column_index]

5

In [147]:
print(my_2d_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [148]:
my_2d_array[2,2]

9

In [149]:
my_2d_array[3,1]

11

In [150]:
my_array = np.array([1,2,3,4,5])

my_array[0,2]

IndexError: too many indices for array

In [7]:
# indexing an ndarray

In [151]:
print(my_2d_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [154]:
np.append( my_2d_array[1, 1:], my_2d_array[2,0] )

array([5, 6, 7])

In [156]:
my_2d_array = np.array([
                        [1,2,3,4,5],
                        [6,7,8,9,10,],
                        [11,12,13,14,15],
                        [16,17,18,19,20]
                        ])

print(my_2d_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [158]:
my_2d_array[1, 1:4]

array([7, 8, 9])

In [160]:
my_2d_array[1:4, 3]

[indexing_the_rows, indexing_the_columns]

array([ 9, 14, 19])

In [163]:
first_row = 1
last_row = 3
column = 3

my_new_data = my_2d_array[first_row:last_row+1, column]

print(my_new_data)

[ 9 14 19]


In [164]:
print(my_2d_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [165]:
my_2d_array[2, 11] 

IndexError: index 11 is out of bounds for axis 1 with size 5

In [8]:
# axis

### problem set


In [103]:
# integer vs logical indexing
# (by example, not explanation)

In [ ]:
# possibly: [arg]where

In [108]:
my_array = np.array([10, 6, 2, 11, 22, 5, 30, 15, 10])

is_greater_than_10 = my_array > 10

print(is_greater_than_10)

# what are all the indices of the values greater than 10?
# correct answer: 3, 4, 6, 7

i = 0
array_greater_than_10 = []
while i < len(my_array):
    if my_array[i] > 10:
        array_greater_than_10 = array_greater_than_10 + [i]
    i = i+1
print(array_greater_than_10)



[False False False  True  True False  True  True False]
[3, 4, 6, 7]


In [114]:
# an easier approach
my_array = np.array([10, 6, 2, 11, 22, 5, 30, 15, 10])

is_greater_than_10 = my_array > 10
print(is_greater_than_10)

print( np.where(is_greater_than_10) )

indices_where_arr_is_greater_than_10 = np.where(is_greater_than_10)
# for reasons we won't go into, take the 0th item of the result
print(indices_where_arr_is_greater_than_10[0])

# summary of the easy approach:
indices_of_interest = np.where(my_array>10)[0]

[False False False  True  True False  True  True False]
(array([3, 4, 6, 7]),)
[3 4 6 7]


### problem set

In [168]:
my_array = np.array([1,2,3,4])

np.max(my_array, axis=0)

4