<hr/>
### Problem 1

__(a)__ Use a `for` loop with a `range` to create a list containing the numbers from 20 to 99.

In [1]:
results = []

for i in range(20, 100):
    results.append(i)
    
print(results)

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


__(b)__ Convert your list into a numpy array.

In [2]:
import numpy as np

In [3]:
array = np.array(results)

print(array)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99]


__(c)__ Create a new numpy array consisting of only the first ten elements (20-29) of the array.

In [4]:
start = array[:10]

print(start)

[20 21 22 23 24 25 26 27 28 29]


__(d)__ Create a new __*list*__ consisting of the last 20 items (80-99) in the original array.

In [5]:
end = array[-20:]

print(end)

[80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


__(e)__ Again consider your array with values from 0-99. 

Set the __first half__ of the elements in this array to 2 times their old value.

For example, the value that was 2 will now be 4.

In [6]:
# copying the previous array
array_copy = np.copy(array)
# compute the length of the first half, using // to force integer division
first_half = len(array_copy) // 2   
# setting the first 
array_copy[:first_half] *= 2
print(array_copy)

[ 40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74
  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108 110
 112 114 116 118  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99]


__(f)__ If it doesn't already, ensure your solution to __e__ works for an array with a different number of elements.

In [7]:
# note that the solution above is agnostic to the length

<hr/>
### Problem 2

__(a)__ Create a new array consisting of the numbers 0 through 10 in steps of __*0.1*__.

In [8]:
# one way to do it, using range
my_range = np.array(range(0, 101)) / 10
print(my_range)

# another, easiesr way to do it, using a built-in numpy function
# this says "give me 101 numbers evenly spaced between 0 to 10"
my_range = np.linspace(0, 10, num=101)
print(my_range)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10. ]
[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5

__(b)__ Create a new array consisting of the square of every element in your array. For example, 3.0 becomes 9.0.

In [9]:
# one way
squares = my_range * my_range
print(squares)

# another way
squares = my_range ** 2
print(squares)

# a third way
squares = np.power(my_range, 2)
print(squares)

[0.000e+00 1.000e-02 4.000e-02 9.000e-02 1.600e-01 2.500e-01 3.600e-01
 4.900e-01 6.400e-01 8.100e-01 1.000e+00 1.210e+00 1.440e+00 1.690e+00
 1.960e+00 2.250e+00 2.560e+00 2.890e+00 3.240e+00 3.610e+00 4.000e+00
 4.410e+00 4.840e+00 5.290e+00 5.760e+00 6.250e+00 6.760e+00 7.290e+00
 7.840e+00 8.410e+00 9.000e+00 9.610e+00 1.024e+01 1.089e+01 1.156e+01
 1.225e+01 1.296e+01 1.369e+01 1.444e+01 1.521e+01 1.600e+01 1.681e+01
 1.764e+01 1.849e+01 1.936e+01 2.025e+01 2.116e+01 2.209e+01 2.304e+01
 2.401e+01 2.500e+01 2.601e+01 2.704e+01 2.809e+01 2.916e+01 3.025e+01
 3.136e+01 3.249e+01 3.364e+01 3.481e+01 3.600e+01 3.721e+01 3.844e+01
 3.969e+01 4.096e+01 4.225e+01 4.356e+01 4.489e+01 4.624e+01 4.761e+01
 4.900e+01 5.041e+01 5.184e+01 5.329e+01 5.476e+01 5.625e+01 5.776e+01
 5.929e+01 6.084e+01 6.241e+01 6.400e+01 6.561e+01 6.724e+01 6.889e+01
 7.056e+01 7.225e+01 7.396e+01 7.569e+01 7.744e+01 7.921e+01 8.100e+01
 8.281e+01 8.464e+01 8.649e+01 8.836e+01 9.025e+01 9.216e+01 9.409e+01
 9.604

__(c)__ Determine how many values in your array are above 6.35. Store the result in a new variable and print it out.

In [10]:
threshold = 6.35
# the most naive way to do it -- count using a for loop
counter = 0
for num in squares:
    if num > threshold:
        counter += 1
        
print(f'Using a for loop, {counter} numbers in the array over {threshold:.2f}')

# a second way to do it - what happens when I compare the array to the threshold?
print(squares > threshold)

# a list of booleans? fascinating? Can we just count them? What if we just take the sum?
total_greater_than_threshold = np.sum(squares > threshold)

print(f'Using a sum, {total_greater_than_threshold} numbers in the array over {threshold:.2f}')




Using a for loop, 75 numbers in the array over 6.35
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True]
Using a sum, 75 numbers in the array over 6.35


__(d)__ Determine all the values in your original array whose squared value is greater than the original. Store these values in a new array and print it out.

In [11]:
# again, starting with a for loop
counter = 0
for i in range(len(squares)):
    if squares[i] > my_range[i]:
        counter += 1
        
print(f'Using a for loop, {counter} numbers have a square greater than the original')

# what if we use numpy instead?
result = np.sum(squares > my_range)
print(f'Using a sum, {result} numbers have a square greater than the original')


Using a for loop, 90 numbers have a square greater than the original
Using a sum, 90 numbers have a square greater than the original


__(e - bonus)__ What fraction of the values satisfied the criteria in __d__? In other words, what fraction of the numbers from 0 to 10 in steps of 0.1 are smaller than their square?

In [12]:
fraction = result / len(squares)
print(f'A proportion of {result}/{len(squares)}={fraction:.4f} have a square greater than the original value')

A proportion of 90/101=0.8911 have a square greater than the original value


<hr/>
### Problem 3

This code loads a numpy array from a data file. It contains the volume in milliliters of various samples found in the laboratory. 

In [13]:
volumes = np.load('volumes.npy')

__(a)__ How many samples do you have?

In [14]:
# using python's built-in length
print(len(volumes))

# using numpy's size attribute of a numpy-array
print(volumes.size)

# using numpy's size function
print(np.size(volumes))

50
50
50


__(b)__ What is the average volume of your samples?

In [15]:
# starting naively, with a for loop
total = 0
for number in volumes:
    total += number
    
average = total / volumes.size
print(f'Using a for loop, the average volume is {average:.4f}')

# using numpy's sum
np_sum_average = np.sum(volumes) / volumes.size
print(f'Using numpy\'s sum, the average volume is {np_sum_average:.4f}')

# using numpy's average directly
np_average = np.average(volumes)
print(f'Using numpy\'s average, the average volume is {np_average:.4f}')

Using a for loop, the average volume is 2.8120
Using numpy's sum, the average volume is 2.8120
Using numpy's average, the average volume is 2.8120


__(c)__ What are the volumes of the smallest and largest sample?

In [16]:
# as before, let's begin with a for loop

# starting with really extreme values
smallest_volume = 1e10
largest_volume = -1e10

for number in volumes:
    if number < smallest_volume:
        smallest_volume = number
    elif number > largest_volume:
        largest_volume = number
        
print(f'Using a for loop, the smallest number is {smallest_volume} and the largest is {largest_volume}')

# let's let numpy do the hard work for us
np_smallest = np.min(volumes)
np_largest = np.max(volumes)

print(f'Using numpy, the smallest number is {np_smallest} and the largest is {np_largest}')

Using a for loop, the smallest number is 0.0 and the largest is 9.3
Using numpy, the smallest number is 0.0 and the largest is 9.3


__(d)__ You want to determine whether you can transfer each of your samples completely into a 5-mL tube without the 5-mL tube overflowing.

Print out a single statement indicating whether or not you can do this. 

If they are, print `"We can transfer all the samples."` Otherwise print `"We cannot transfer all the samples."`

In [17]:
threshold = 5.0

# let's start with a for loop
can_transfer_all = True
for number in volumes:
    if number > threshold:
        can_transfer_all = False
        break
        
print(f'Using a for lop, can we transfer all? {can_transfer_all}')

# let's do with numpy, using the compare-and-sum approach from above
total_above_treshold = np.sum(volumes > threshold)
any_above_treshold = total_above_treshold == 0

print(f'Using numpy sum and compare, can we transfer all? {any_above_treshold}')

# now let's do it the easiest numpy way
np_can_transfer = np.all(volumes <= threshold)
print(f'Using numpy\'s all function, can we transfer all? {np_can_transfer}')

# and an alternative easy way
np_alt_can_transfer = not np.any(volumes > threshold)
print(f'Using numpy\'s any function, can we transfer all? {np_alt_can_transfer}')


Using a for lop, can we transfer all? False
Using numpy sum and compare, can we transfer all? False
Using numpy's all function, can we transfer all? False
Using numpy's any function, can we transfer all? False


__(e)__ Load in a second array of the tube sizes that currently contain our samples. The tube size data are stored in a file called `'tube_sizes.npy'` .

In [18]:
tube_sizes = np.load('tubes.npy')

__(f)__ Are all the tubes the same size? Print out your answer.

In [19]:
# let's try using a for loop
# if these are all the same, they should all be equal to the first element
first_size = tube_sizes[0]
all_same = True
for size in tube_sizes:
    # if any size in the array is not the same as the first one
    if size != first_size:
        # set the all_same variable to False, and break out of the for loop
        all_same = False
        break
        
print(f'Using a for loop, are all sizes the same? {all_same}')

# Using np.all, making the same test as above
np_all_same = np.all(tube_sizes == first_size)
print(f'Using numpy.all, are all sizes the same? {np_all_same}')

# Using np.unique, to ask how many unique values there are?
np_unique_len = len(np.unique(tube_sizes))
print(f'Using numpy.unique, there are {np_unique_len} unique values, and therefore, are all sizes the same? {np_unique_len == 1}')

Using a for loop, are all sizes the same? False
Using numpy.all, are all sizes the same? False
Using numpy.unique, there are 3 unique values, and therefore, are all sizes the same? False


__(g)__ If they are all the same size, print the size. If they are not all the same size, print out the number of distinct tube sizes in our collection.

In [20]:
# let's start using a for loop

# we'll keep track of sizes we've already found
found_sizes = []
# go through every size in the tube_sizes array
for size in tube_sizes:
    # have we found this size yet?
    if size not in found_sizes:
        print(f'Found a new size: {size}')
        found_sizes.append(size)
        
# now do what the question asked
if len(found_sizes) == 1:
    print(f'Found only one size, and it is {found_sizes[0]}')
else:
    print(f'Found {len(found_sizes)} unique sizes')
    
# can we do this with numpy? of course!

unique_values = np.unique(tube_sizes)
if len(unique_values) == 1:
    print(f'Using numpy, found only one size, and it is {unique_values[0]}')
else:
    print(f'Using numpy, found {len(unique_values)} unique sizes')

Found a new size: 10
Found a new size: 3
Found a new size: 5
Found 3 unique sizes
Using numpy, found 3 unique sizes


__(h)__ Load in a third array from the file `'volumes_to_add.npy'`. 

This array consists of volumes of a chemical we want to add to the current tubes. For instance, the first item in this array is the volume we want to add to the first tube. 

In [21]:
volumes_to_add = np.load('volumes_to_add.npy')

__(i)__ Determine whether any tubes will overflow if we add the desired volume.

In [22]:
# as always, we begin with a for loop
any_overflow = False
# go through every index in the arrays
for i in range(tube_sizes.size):
    # check if the size of the tube is smaller than 
    # the current volume + the volume to add
    if tube_sizes[i] < volumes[i] + volumes_to_add[i]:
        # if it is, print, mark it in the any_overflow variable, and break
        print(f'Using a for loop, tube #{i} will overflow!')
        any_overflow = True
        break

# if the any_overflow variable is unmarked, print that no tubes will overflow
if not any_overflow:
    print('Using a for loop, no tubes will overflow')
    
# let's do it with numpy:
numpy_will_overflow = np.any(tube_sizes < volumes + volumes_to_add)
print(f'Using numpy, will any tubes overflow? {numpy_will_overflow}')

Using a for loop, tube #2 will overflow!
Using numpy, will any tubes overflow? True


__(j)__  If any tubes will overflow, determine the total amount of overflow fluid after transferring all chemicals into their tubes.

In [23]:
# let us for loop:
total_overflow = 0
# go through every index in the array
for i in range(tube_sizes.size):
    # check if the size of the tube is smaller than 
    # the current volume + the volume to add
    potential_overflow = volumes[i] + volumes_to_add[i] - tube_sizes[i]
    if potential_overflow > 0 :
        # if it is, add the overflow to the total_overflow
        total_overflow += potential_overflow
        
print(f'Using a for loop, the total overflow is {total_overflow:.3f} mL')
print()

# How can we do it using numpy? 

# we compute the potential overflow (disparity between tube size and volume + volume to add)
potential_overflows = volumes + volumes_to_add - tube_sizes
print(potential_overflows)
# we now ask numpy which tubes are actually overflowing:
overflowing_tubes = potential_overflows > 0
print(overflowing_tubes)
# we can now use this array to index the first one:
print(potential_overflows[overflowing_tubes])
# and use this to compute the sum
np_total_overflow = np.sum(potential_overflows[overflowing_tubes])
print()
print(f'Using numpy, the total overflow is {np_total_overflow:.3f} mL')

# Can we do it with one line in numpy? Of course!
# for each element in the array, take the maximum between the amount of overflow and 0
# thus, if any would overflow, take that value; and if there is room in the tube, take 0
np_total_overflow_2 = np.sum(np.maximum(volumes + volumes_to_add - tube_sizes, 0))
print(f'Using one numpy line, the total overflow is {np_total_overflow_2:.3f} mL')


Using a for loop, the total overflow is 18.150 mL

[-8.   -0.45  0.95 -1.9  -0.6  -0.25 -0.55  1.05  1.85 -2.45  1.3  -1.35
  1.05 -0.65 -2.05 -3.5   0.5  -1.    1.2  -0.6  -0.75  1.15 -1.85  0.95
 -3.45  0.4   2.25  0.25  0.   -9.05 -0.9   1.35 -1.75 -1.1   1.   -0.55
 -3.35 -1.55  0.35 -1.55 -2.45 -1.85  0.15  0.65  0.55 -4.2  -2.15 -2.6
 -1.4   1.2 ]
[False False  True False False False False  True  True False  True False
  True False False False  True False  True False False  True False  True
 False  True  True  True False False False  True False False  True False
 False False  True False False False  True  True  True False False False
 False  True]
[0.95 1.05 1.85 1.3  1.05 0.5  1.2  1.15 0.95 0.4  2.25 0.25 1.35 1.
 0.35 0.15 0.65 0.55 1.2 ]

Using numpy, the total overflow is 18.150 mL
Using one numpy line, the total overflow is 18.150 mL


<hr/>
### Problem 4

__(a)__ Create a 2D numpy array with 5 rows and 10 columns. Each row should contain the numbers 0 to 9.

In [24]:
# let's start with a reasonably simple version

# initialize an output of the appropriate size
out = np.zeros((5, 10))
# grab the number of rows
print(f'The shape of the output is (rows, cols) = {out.shape}')
num_rows = out.shape[0]

for i in range(num_rows):
    out[i, :] = np.arange(10)
    
print(out)

# another way to do this is with numpy's matlib, which is a bit like matlab:
import numpy.matlib
second_out = np.matlib.repmat(np.arange(10), 5, 1)
print(second_out)

The shape of the output is (rows, cols) = (5, 10)
[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


__(b)__ Modify your array so that every other row is reversed, i.e. every other row should now contain the numbers from 9 to 0, while the other rows remain unaffected.

In [25]:
# We can, again, using a for loop:
for i in range(0, out.shape[0], 2):
    # we first take the i'th row, and then reverse it
    out[i, :] = out[i, :][::-1]
    
print(out)

# Can we do it in one line?
# it's easiest using the numpy flip function
second_out[range(0, out.shape[0], 2),:] = np.flip(second_out[range(0, out.shape[0], 2),:], 1)
print(second_out)

[[9. 8. 7. 6. 5. 4. 3. 2. 1. 0.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [9. 8. 7. 6. 5. 4. 3. 2. 1. 0.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [9. 8. 7. 6. 5. 4. 3. 2. 1. 0.]]
[[9 8 7 6 5 4 3 2 1 0]
 [0 1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1 0]
 [0 1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1 0]]


__(c)__ Determine the maximum value found in each column. Print out the resulting array, which should contain one value per column of the original array.

In [26]:
# using a for loop:
num_rows = out.shape[0]
num_cols = out.shape[1]
# create a result to store the output
results = np.zeros((num_cols,))

for j in range(num_cols):
    # we first take the j'th col
    col = out[:,j]
    col_max = 0
    # now loop through every row in it
    for i in range(num_rows):
        # if it's larger, store it as the new column maximum
        if col[i] > col_max:
            col_max = col[i]
    
    # save the column-wise maximum
    results[j] = col_max
            
print(f'Using nested for loops, the column-wise maxima are {results}')

# Can we do it in numpy? of course!
np_results = np.max(second_out, axis=0)
print(f'Using a numpy function, the column-wise maxima are {np_results}')

Using nested for loops, the column-wise maxima are [9. 8. 7. 6. 5. 5. 6. 7. 8. 9.]
Using a numpy function, the column-wise maxima are [9 8 7 6 5 5 6 7 8 9]


__(d)__ Determine the sum of each row in the original array. Print out the resulting array, which should contain one value per row of the original array.

In [27]:
# Once more into the for loop:
num_rows = out.shape[0]
num_cols = out.shape[1]
# create a result to store the output
row_sums = np.zeros((num_rows,))

for i in range(num_rows):
    # we first take the i'th row
    row = out[i, :]
    row_sum = 0
    # now loop through every row in it
    for j in range(num_cols):
        row_sum += row[j]
    
    # save the column-wise maximum
    row_sums[i] = row_sum
            
print(f'Using nested for loops, the row sums are {row_sums}')

# And in a single numpy line
row_sums = np.sum(second_out, axis=1)
print(f'Using a numpy function, the row sums maxima are {row_sums}')

Using nested for loops, the row sums are [45. 45. 45. 45. 45.]
Using a numpy function, the row sums maxima are [45 45 45 45 45]


__(e)__ Create a new 2D array with 10 rows and 10 columns. All the elements in the array should be equal to zero.

In [28]:
zeros = np.zeros((10, 10))
second_zeros = np.zeros((10, 10))

__(f)__ Modify your array so that the diagonal elements are all equal to 1.

(The first diagonal element is the one in the first row, first column. The second diagonal element is the one in the second row, second column. And so on.)

In [29]:
# another for loop:
num_rows = zeros.shape[0]

for i in range(num_rows):
    zeros[i, i] = 1
    
print(zeros)

# and with a numpy call
np.fill_diagonal(second_zeros, 1)
print(second_zeros)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


<hr/>
### Problem 5

__(a)__ Load the dataset in the file called `"songs.npy"`.

These are data collected from an experiment. In each trial, a fly was placed into a chamber for one minute and we recorded the number of songs it sang. It was then taken out, and another trial was repeated. We collected 10 trials per fly.

In this array, each row represents one fly.  

Each column represents one of the trials, with column 0 being the first, and column 9 being the last.

How many flies are in our dataset?

In [30]:
songs = np.load('songs.npy')
print(songs.shape)
print(f'There are {songs.shape[0]} flies, each with {songs.shape[1]} trials')

(22, 10)
There are 22 flies, each with 10 trials


__(b)__ Calculate a single number: the total number of songs sang by all flies.

In [31]:
# for loop time
num_rows, num_cols = songs.shape
total_songs = 0
for i in range(num_rows):
    for j in range(num_cols):
        total_songs += songs[i, j]
        
print(f'Using nested for loops, the total number of songs is {total_songs}')

# and in numpy
np_sum = np.sum(total_songs)
print(f'Using a numpy function, the total number of songs is {np_sum}')

Using nested for loops, the total number of songs is 2892
Using a numpy function, the total number of songs is 2892


__(c)__ Calculate how many total songs each fly sang, and print out an array containing the result.

In [32]:
# each fly => row-wise sums => same code as before:
num_rows, num_cols = songs.shape
# create a result to store the output
row_sums = np.zeros((num_rows,))

for i in range(num_rows):
    # we first take the i'th row
    row = songs[i, :]
    row_sum = 0
    # now loop through every row in it
    for j in range(num_cols):
        row_sum += row[j]
    
    # save the column-wise maximum
    row_sums[i] = row_sum
            
print(f'Using nested for loops, the per-fly sums are {row_sums}')

# And in a single numpy line
row_sums = np.sum(songs, axis=1)
print(f'Using a numpy function, the row sums maxima are {row_sums}')

Using nested for loops, the per-fly sums are [131. 124. 122. 140. 110. 173. 131. 115. 132. 144. 131. 153. 132. 130.
 143. 115. 151. 115. 134. 105. 102. 159.]
Using a numpy function, the row sums maxima are [131 124 122 140 110 173 131 115 132 144 131 153 132 130 143 115 151 115
 134 105 102 159]


__(d)__ Calculate the average (across flies) number of songs sang in the 5th trial.

In [33]:
# average cross fly => pull index 4 (the fifth trial) for every row

num_rows, num_cols = songs.shape
# create a result to store the output
fifth_trial_sum = 0

for i in range(num_rows):
    fifth_trial_sum += songs[i, 4]
    
fifth_trial_average = fifth_trial_sum / num_rows
            
print(f'Using a for loop, the fifth trial average is {fifth_trial_average:.3f}')

# and using a single numpy call:
# songs[:, 4] means take the element in index 4 from every row
np_average = np.average(songs[:, 4])

print(f'Using a numpy function, the fifth trial average is {np_average:.3f}')

Using a for loop, the fifth trial average is 13.045
Using a numpy function, the fifth trial average is 13.045


__(e)__ Compute the fraction of flies that sang more than 2 songs in their first trial.

In [34]:
# fraction in first trial => iterate across rows, checking the first trial (index 0) of each
num_rows, num_cols = songs.shape
threshold = 2
first_trial_counter = 0

for i in range(num_rows):
    # index 0 is the first trial
    if songs[i, 0] > threshold:
        first_trial_counter += 1
        
print(f'Using a for loop, a fraction of {first_trial_counter}/{num_rows}={first_trial_counter / num_rows:.3f} flies sang in the first trial')

# Using numpy:
first_trial = songs[:, 0]
first_trial_above_threshold = first_trial > 2
first_trial_sum = np.sum(first_trial_above_threshold)
first_trial_proportion = np.average(first_trial_above_threshold)
print(f'Using numpy, a fraction of {first_trial_sum}/{num_rows}={first_trial_proportion:.3f} flies sang in the first trial')

# And in one numpy line
one_line_first_trial_prop = np.average(songs[:, 0] > threshold)
print(f'And in one numpy line, the proportion first trials where the flies sang are {one_line_first_trial_prop:.3f}')

Using a for loop, a fraction of 11/22=0.500 flies sang in the first trial
Using numpy, a fraction of 11/22=0.500 flies sang in the first trial
And in one numpy line, the proportion first trials where the flies sang are 0.500


__(f - bonus)__ For each fly, determine the first trial in which it sang more than 10 songs.

In [35]:
# We could solve this using a nested for loop:
num_rows, num_cols = songs.shape
threshold = 10
# initialize an array of -1's, we'll use -1 to signifiy "never sang over 10 songs in a trial"
first_trial_over = np.ones((num_rows,)) * -1

for i in range(num_rows):
    for j in range(num_cols):
        # If we find what we're looking for
        if songs[i, j] > threshold:
            # Save this first trial index over 10
            first_trial_over[i] = j
            # Break out of only the inner for loop
            break
            

print(f'Each fly (in order) first sang over ten songs in the following trials: {first_trial_over}')


# And using a single numpy call
# axis=1 signifies go across columns, so for every row
np_first_over = np.argmax(songs > threshold, axis=1)
print(f'And using numpy: {np_first_over}')

Each fly (in order) first sang over ten songs in the following trials: [4. 4. 4. 4. 2. 3. 4. 3. 4. 4. 3. 4. 3. 6. 3. 4. 2. 4. 3. 4. 4. 2.]
And using numpy: [4 4 4 4 2 3 4 3 4 4 3 4 3 6 3 4 2 4 3 4 4 2]


<hr/>
### Problem 6 (bonus)

Write a function that accepts as input a 2d array representing an image. If the image is all black or all white, return `False`. Otherwise, return the average value of the pixels in image.

For this question, assume that `0` corresponds to black, `1` corresponds to white, and all values between `0` and `1` are colors or grey levels.

You can load the files `black_image.npy`, `white_image.npy`, and `photo.npy` to use for testing.

In [36]:
# There are many ways to do this. Here's one:
BLACK = 0
WHITE = 1

def is_all_bw(image):
    # If the image is all black or white, it must all be equal the value of the first pixel
    first_pixel = image[0, 0]
    all_same = np.all(image == first_pixel)
    # if it is, verify that this first pixel is indeed black or white:
    if all_same and (first_pixel == BLACK or first_pixel == WHITE):
        # All the same and all black or all white, return False
        return False
    
    # If we arrived here, the image isn't all black or white, so compute the average
    return np.average(image)

In [37]:
black_image = np.load('black_image.npy')
white_image = np.load('white_image.npy')
photo = np.load('photo.npy')

In [38]:
print(f'For the black image, we receive {is_all_bw(black_image)}')
print(f'For the white image, we receive {is_all_bw(white_image)}')
print(f'For the photo, we receive {is_all_bw(photo)}')

For the black image, we receive False
For the white image, we receive False
For the photo, we receive 489.85768
